name: Test
on:
  push:
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang
        uses: erlef/setup-beam@v1
        with:
          version-type: strict
          otp-version: '25.0-rc3'
      - run: escript test.erl
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang
        uses: erlef/setup-beam@v1
        with:
          version-type: strict
          otp-version: '25.1'
      - run: systeminfo
      - run: escript test.erl
